package com.sample
 
declare Question
	question : String
	answer : String
end

declare FinalAnswer
	answer : String
end

query "Questions without answers"
	question : Question(answer == null)
end

query "Get answer"
	answer : FinalAnswer()
end
 
rule "Init"
    when
        
    then
        insert(new Question("Do you need to make money?", null));
end

rule "MoneyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
	then
		insert(new Question("Do you want to use your brain?", null));
end

rule "MoneyNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
	then
		insert(new Question("Do you have a bit of money to spend?", null));
end

rule "MoneySpendNo"
	when
		Question(question == "Do you have a bit of money to spend?", answer == "No")
	then
		insert(new Question("Do you have artistic talent?", null));
end

rule "MoneySpendYes"
	when
		Question(question == "Do you have a bit of money to spend?", answer == "Yes")
	then
		insert(new Question("Do you want to stay in Hamilton?", null));
end

rule "ArtisticTalentNo"
	when
		Question(question == "Do you have artistic talent?", answer == "No")
	then
		insert(new FinalAnswer("INTERN/APPRENTICE"));
end

rule "ArtisticTalentYes"
	when
		Question(question == "Do you have artistic talent?", answer == "Yes")
	then
		insert(new FinalAnswer("PERFORMER/MUSICIAN"));
end

rule "HamiltonNo"
	when
		Question(question == "Do you want to stay in Hamilton?", answer == "No")
	then
		insert(new FinalAnswer("WORLD TRAVELLER"));
end

rule "HamiltonYes"
	when
		Question(question == "Do you want to stay in Hamilton?", answer == "Yes")
	then
		insert(new Question("Do you want to use your brain?", null));
end

rule "BrainNo_MoneyNo"
	when
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you need to make money?", answer == "No")
	then
		insert(new FinalAnswer("COUCH POTATO"));
end

rule "BrainYes_MoneyNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "No")
	then
		insert(new FinalAnswer("SUMMER STUDENT"));
end

rule "BrainNo_MoneyYes"
	when
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you need to make money?", answer == "Yes")
	then
		System.out.println("Not implemented yet.");
end

rule "BrainYes_MoneyYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
	then
		System.out.println("Not implemented yet.");
end