package com.sample
 
declare Question
	question : String
	answer : String
end

declare FinalAnswer
	answer : String
end

query "Questions without answers"
	question : Question(answer == null)
end

query "Get answer"
	answer : FinalAnswer()
end
 
rule "Init"
    when        
    then
        insert(new Question("Do you need to make money?", null));
end

rule "MoneyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
	then
		insert(new Question("Do you want to use your brain?", null));
end

rule "MoneyNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
	then
		insert(new Question("Do you have a bit of money to spend?", null));
end

rule "MoneySpendNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "No")
	then
		insert(new Question("Do you have artistic talent?", null));
end

rule "MoneySpendYes"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "Yes")
	then
		insert(new Question("Do you want to stay in Hamilton?", null));
end

rule "ArtisticTalentNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "No")
		Question(question == "Do you have artistic talent?", answer == "No")
	then
		insert(new FinalAnswer("INTERN/APPRENTICE"));
end

rule "ArtisticTalentYes"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "No")
		Question(question == "Do you have artistic talent?", answer == "Yes")
	then
		insert(new FinalAnswer("PERFORMER/MUSICIAN"));
end

rule "HamiltonNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "Yes")
		Question(question == "Do you want to stay in Hamilton?", answer == "No")
	then
		insert(new FinalAnswer("WORLD TRAVELLER"));
end

rule "HamiltonYes"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "Yes")
		Question(question == "Do you want to stay in Hamilton?", answer == "Yes")
	then
		insert(new Question("Do you want to use your brain?", null));
end

rule "BrainNo_MoneyNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "Yes")
		Question(question == "Do you want to stay in Hamilton?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
	then
		insert(new FinalAnswer("COUCH POTATO"));
end

rule "BrainYes_MoneyNo"
	when
		Question(question == "Do you need to make money?", answer == "No")
		Question(question == "Do you have a bit of money to spend?", answer == "Yes")
		Question(question == "Do you want to stay in Hamilton?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "Yes")
	then
		insert(new FinalAnswer("SUMMER STUDENT"));
end

rule "BrainNo_MoneyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")		
	then
		insert(new Question("Do you want to work outside?", null));
end

rule "BrainYes_MoneyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "Yes")
	then
		insert(new Question("Do you want to work in an office/lab?", null));
end

rule "OfficeNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
	then
		insert(new Question("Do you want to be your own boss?", null));
end

rule "OfficeYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
	then
		insert(new Question("Do you want to work at McMaster?", null));
end

rule "BossNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "No")
	then
		insert(new Question("Do you want to work outside?", null));
end

rule "BossYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
	then
		insert(new Question("Are you good at academics?", null));
end

rule "OutsideNo_BrainYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
	then
		insert(new FinalAnswer("MUSEUM INTERPRETER"));
end

rule "OutsideYes_BrainYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
	then
		insert(new FinalAnswer("SUMMER CAMP LEADER"));
end

rule "AcademicsNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
		Question(question == "Are you good at academics?", answer == "No")
	then
		insert(new Question("Are you artistic?", null));
end

rule "AcademicsYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
		Question(question == "Are you good at academics?", answer == "Yes")
	then
		insert(new Question("Are you good at teaching?", null));
end

rule "ArtisticNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
		Question(question == "Are you good at academics?", answer == "No")
		Question(question == "Are you artistic?", answer == "No")
	then
		insert(new FinalAnswer("SMALL-BUSINESS OWNER"));
end

rule "ArtisticYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
		Question(question == "Are you good at academics?", answer == "No")
		Question(question == "Are you artistic?", answer == "Yes")
	then
		insert(new FinalAnswer("PERFORMER/BUSKER"));
end

rule "TeachingNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
		Question(question == "Are you good at academics?", answer == "Yes")
		Question(question == "Are you good at teaching?", answer == "No")
	then
		insert(new FinalAnswer("USRA RECIPENT"));
end

rule "TeachingYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "No")
		Question(question == "Do you want to be your own boss?", answer == "Yes")
		Question(question == "Are you good at academics?", answer == "Yes")
		Question(question == "Are you good at teaching?", answer == "Yes")
	then
		insert(new FinalAnswer("TUTOR"));
end

rule "McMasterNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "No")
	then
		insert(new Question("Are you decent with computers?", null));
end

rule "McMasterYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "Yes")
	then
		insert(new Question("Are you good at science?", null));
end

rule "ScienceNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "Yes")
		Question(question == "Are you good at science?", answer == "No")
	then
		insert(new FinalAnswer("MCMASTER OFFICE ASSISTANT"));
end

rule "ScienceYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "Yes")
		Question(question == "Are you good at science?", answer == "Yes")
	then
		insert(new FinalAnswer("RESEARCH ASSISTANT"));
end

rule "ComputersNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "No")
		Question(question == "Are you decent with computers?", answer == "No")
	then
		insert(new FinalAnswer("CIVIL SERVANT"));
end

rule "ComputersYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "No")
		Question(question == "Are you decent with computers?", answer == "Yes")
	then
		insert(new Question("Are you good at coding?", null));
end

rule "CodingNo"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "No")
		Question(question == "Are you decent with computers?", answer == "Yes")
		Question(question == "Are you good at coding?", answer == "No")
	then
		insert(new FinalAnswer("ADMIN ASSISTANT/SECRETARY"));
end

rule "CodingYes"
	when
		Question(question == "Do you want to use your brain?", answer == "Yes")
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to work in an office/lab?", answer == "Yes")
		Question(question == "Do you want to work at McMaster?", answer == "No")
		Question(question == "Are you decent with computers?", answer == "Yes")
		Question(question == "Are you good at coding?", answer == "Yes")
	then
		insert(new FinalAnswer("SOFTWARE DEVELOPER"));
end

rule "WorkOutsideYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
	then
		insert(new Question("Are you okay with hard physical labour?", null));
end

rule "WorkOutsideNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
	then
		insert(new Question("Do you want to wirk with food/drink?", null));
end

rule "PhysicalLabourYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "Yes")
	then
		insert(new Question("Are you okay with showering infrequently?", null));
end

rule "PhysicalLabourNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "No")
	then
		insert(new Question("Do you like camping?", null));
end

rule "CampingYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "No")
		Question(question == "Do you like camping?", answer == "Yes")
	then
		insert(new FinalAnswer("PROVINCIAL PARK EMPLOYEE"));
end

rule "CampingNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "No")
		Question(question == "Do you like camping?", answer == "No")
	then
		insert(new FinalAnswer("FRUIT PICKER"));
end

rule "ShoweringInfrequentlyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "Yes")
		Question(question == "Are you okay with showering infrequently?", answer == "Yes")
	then
		insert(new FinalAnswer("TREE PLANTER"));
end

rule "ShoweringInfrequentlyNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "Yes")
		Question(question == "Are you okay with showering infrequently?", answer == "No")
	then
		insert(new Question("Do you like animals?", null));
end

rule "AnimalsYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "Yes")
		Question(question == "Are you okay with showering infrequently?", answer == "No")
		Question(question == "Do you like animals?", answer == "Yes")
	then
		insert(new FinalAnswer("FARM LABOURER"));
end

rule "AnimalsNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "Yes")
		Question(question == "Are you okay with hard physical labour?", answer == "Yes")
		Question(question == "Are you okay with showering infrequently?", answer == "No")
		Question(question == "Do you like animals?", answer == "No")
	then
		insert(new FinalAnswer("LANDSCAPER"));
end

rule "FoodOrDrinkYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
	then
		insert(new Question("Do you have good people skills?", null));
end

rule "FoodOrDrinkNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
	then
		insert(new Question("Are you good at telling people what to do?", null));
end

rule "LeaderYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "Yes")
	then
		insert(new Question("Are you bulky?", null));
end

rule "LeaderNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "No")
	then
		insert(new Question("Are you fine with travelling?", null));
end

rule "TravellingYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "No")
		Question(question == "Are you fine with travelling?", answer == "Yes")
	then
		insert(new FinalAnswer("BRAND PROMOTER"));
end

rule "TravellingNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "No")
		Question(question == "Are you fine with travelling?", answer == "No")
	then
		insert(new Question("Are you afraid of needles?", null));
end

rule "AfraidNeedlesYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "No")
		Question(question == "Are you fine with travelling?", answer == "No")
		Question(question == "Are you afraid of needles?", answer == "Yes")
	then
		insert(new FinalAnswer("SALES CLERK"));
end

rule "AfraidNeedlesNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "No")
		Question(question == "Are you fine with travelling?", answer == "No")
		Question(question == "Are you afraid of needles?", answer == "No")
	then
		insert(new FinalAnswer("MEDICAL TEST SUBJECT"));
end

rule "BulkyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "Yes")
		Question(question == "Are you bulky?", answer == "Yes")
	then
		insert(new FinalAnswer("SECURITY GUARD/BOUNCER"));
end

rule "BulkyNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "Yes")
		Question(question == "Are you bulky?", answer == "No")
	then
		insert(new Question("Are you a good swimmer?", null));
end

rule "SwimmerYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "Yes")
		Question(question == "Are you bulky?", answer == "No")
		Question(question == "Are you a good swimmer?", answer == "Yes")
	then
		insert(new FinalAnswer("LIFEGUARD"));
end

rule "SwimmerNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "No")
		Question(question == "Are you good at telling people what to do?", answer == "Yes")
		Question(question == "Are you bulky?", answer == "No")
		Question(question == "Are you a good swimmer?", answer == "No")
	then
		insert(new FinalAnswer("SPORT REFEREE"));
end

rule "PeopoleSkillsYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "Yes")
	then
		insert(new Question("Do you know the difference between a Manhattan and an old - fashioned?", null));
end

rule "PeopleSkillsNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "No")
	then
		insert(new Question("Do you mind getting a bit greasy?", null));
end

rule "MindGettingGreasyYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "No")
		Question(question == "Do you mind getting a bit greasy?", answer == "Yes")
	then
		insert(new FinalAnswer("GROCERY STORE EMPLOYEE"));
end

rule "MindGettingGreasyNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "No")
		Question(question == "Do you mind getting a bit greasy?", answer == "No")
	then
		insert(new Question("Do you like burgers?", null));
end

rule "BurgersYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "No")
		Question(question == "Do you mind getting a bit greasy?", answer == "No")
		Question(question == "Do you like burgers?", answer == "Yes")
	then
		insert(new FinalAnswer("FAST FOOD RESTAURANT EMPLOYEE"));
end

rule "BurgersNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "No")
		Question(question == "Do you mind getting a bit greasy?", answer == "No")
		Question(question == "Do you like burgers?", answer == "No")
	then
		insert(new FinalAnswer("PREP COOK/DISHWASHER"));
end

rule "Manhattan_oldFashionedDifferenceYes"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "Yes")
		Question(question == "Do you know the difference between a Manhattan and an old - fashioned?", answer == "Yes")
	then
		insert(new FinalAnswer("BARTENDER"));
end

rule "Manhattan_oldFashionedDifferenceNo"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
		Question(question == "Do you want to use your brain?", answer == "No")
		Question(question == "Do you want to work outside?", answer == "No")
		Question(question == "Do you want to wirk with food/drink?", answer == "Yes")
		Question(question == "Do you have good people skills?", answer == "Yes")
		Question(question == "Do you know the difference between a Manhattan and an old - fashioned?", answer == "No")
	then
		insert(new FinalAnswer("BARRISTA"));
end
