package com.sample
 
declare Question
	question : String
	answer : String
end

declare FinalAnswer
	answer : String
end

query "Questions without answers"
	question : Question(answer == null)
end
 
rule "Init"
    when
        
    then
        insert(new Question("Do you need to make money?", null));
end

rule "YesPlaceHolder"
	when
		Question(question == "Do you need to make money?", answer == "Yes")
	then
		System.out.println("Answer is yes.");	
end

rule "NoPlaceHolder"
	when
		Question(question == "Do you need to make money?", answer == "No")
	then
		System.out.println("Answer is no.");	
end